# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- Project-05/Project-05-Movies-KeyVault-Temp

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.slnf'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#- task: DotNetCoreCLI@2
#  displayName: Build Console App
#  inputs:
#    command: build
#    projects: 'BDF.DVDCentral.UIConsole/BDF.DVDCentral.UIConsole.csproj'
#    arguments: '--configuration Debug' 

- task: DotNetCoreCLI@2
  displayName: Build API Project
  inputs:
    command: build
    projects: 'BDF.DVDCentral.API/BDF.DVDCentral.API.csproj'
    arguments: '--configuration Debug'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'BDF.DVDCentral.UIConsole\bin\Debug\net10.0'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)/BDF.DVDCentral.UIConsole.zip'
    replaceExistingArchive: true   

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container' 