# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:

#- task: AzureKeyVault@1
#  inputs:
#    azureSubscription: 'AzureConnection'                ## YOUR_SERVICE_CONNECTION_NAME
#    KeyVaultName: 'kv-101521081-120212964'                         ## YOUR_KEY_VAULT_NAME
#    SecretsFilter: 'Connection-String-Prod'         ## YOUR_SECRET_NAME. Default value: *
#    RunAsPreJob: false                                   ## Make the secret(s) available to the whole job

- task: PowerShell@2
  displayName: Display version of app
  inputs:
    targetType: 'inline'
    #script: 'Write-Host "Connection String: $(Connection-String-Prod)"' 
    script: 'Write-Host "Callers ID: $(Build.RequestedForId)"'


