// <auto-generated />
using System;
using BDF.DVDCentral.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDF.DVDCentral.PL.Migrations
{
    [DbContext(typeof(DVDCentralEntities))]
    [Migration("20260414184513_AddStoredProc_spGetMovies")]
    partial class AddStoredProc_spGetMovies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.spGetMoviesResult", b =>
                {
                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InStkQty")
                        .HasColumnType("int");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("spGetMoviesResult");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_tblCustomer_Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblCustomer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("85750aea-fda2-4221-941e-de46f36afef5"),
                            Address = "453 Oak Street",
                            City = "Fond du Lac",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Phone = "9205879797",
                            State = "WI",
                            UserId = new Guid("4aaad1ee-15fa-4d81-8717-6b9317059137"),
                            Zip = "54935"
                        },
                        new
                        {
                            Id = new Guid("f38ad6db-d2c7-43a4-8151-01dc654b27da"),
                            Address = "987 Willow Road",
                            City = "Slinger",
                            FirstName = "John",
                            LastName = "Doro",
                            Phone = "9202623345",
                            State = "WI",
                            UserId = new Guid("6bf60220-ad00-45f0-921d-5e3d14b4d4e4"),
                            Zip = "56495"
                        },
                        new
                        {
                            Id = new Guid("07dc5e16-ce6e-42f9-be3b-fd5f699c2da6"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Brian",
                            LastName = "Foote",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("01ec4844-5259-453b-8784-f9bfe718fcf3"),
                            Zip = "53142"
                        },
                        new
                        {
                            Id = new Guid("c3ed8bc1-4b1a-4620-ac03-faf55c1dc6ac"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Other",
                            LastName = "Other",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("01ec4844-5259-453b-8784-f9bfe718fcf3"),
                            Zip = "53142"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblDirector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblDirector_Id");

                    b.ToTable("tblDirector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("82c72373-7dd2-4c75-95f1-a98feed67835"),
                            FirstName = "John",
                            LastName = "Avildsen"
                        },
                        new
                        {
                            Id = new Guid("a882e5ae-aecc-433f-a4e1-706f4acdf76b"),
                            FirstName = "Steven",
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = new Guid("07b131b9-1add-4473-9528-2941f5655992"),
                            FirstName = "Rob",
                            LastName = "Reiner"
                        },
                        new
                        {
                            Id = new Guid("2c43d0de-2305-42e9-a24b-7741d2b13cf5"),
                            FirstName = "George",
                            LastName = "Lucas"
                        },
                        new
                        {
                            Id = new Guid("36473983-e830-4e69-95db-c6830df7d541"),
                            FirstName = "Clint",
                            LastName = "Eastwood"
                        },
                        new
                        {
                            Id = new Guid("09afb148-1700-4a2a-b229-2e3b2ccf153b"),
                            FirstName = "Other",
                            LastName = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblFormat_Id");

                    b.ToTable("tblFormat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("74503613-bded-4a75-8edc-29246e0597fe"),
                            Description = "VHS"
                        },
                        new
                        {
                            Id = new Guid("c547a498-d8a7-4a04-a3b8-235fdb0c8fa2"),
                            Description = "DVD"
                        },
                        new
                        {
                            Id = new Guid("60827f42-c368-4fef-ba34-610b68626694"),
                            Description = "Blu-Ray"
                        },
                        new
                        {
                            Id = new Guid("a2f2856a-efd1-4a87-a6c3-c4e293d10071"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGenre_Id");

                    b.ToTable("tblGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("74ad856b-3978-46b4-9c99-5ac11281d12d"),
                            Description = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("6419e69d-043f-466e-b320-dd4586cf00fa"),
                            Description = "Action"
                        },
                        new
                        {
                            Id = new Guid("3e87b47b-657b-4e0b-8a55-59241604752a"),
                            Description = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("3b7f0077-9754-42d5-a440-eb3d7f9d05a7"),
                            Description = "Horror"
                        },
                        new
                        {
                            Id = new Guid("b7f9b549-e525-4545-baad-aa0d4692e1a5"),
                            Description = "Romance"
                        },
                        new
                        {
                            Id = new Guid("8a4a0eb1-03d0-4bcc-a085-24e95ce00575"),
                            Description = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("24575a54-34c9-46f6-ba14-2d74c04aa7c1"),
                            Description = "Musical"
                        },
                        new
                        {
                            Id = new Guid("acc98b10-28f1-427b-b466-0977d7ee09e1"),
                            Description = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("8a411452-6eb3-46a1-b49f-9a84535d1130"),
                            Description = "Western"
                        },
                        new
                        {
                            Id = new Guid("d1d7c595-8870-48c9-860b-176d5c4d597b"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("InStkQty")
                        .HasColumnType("int");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMovie_Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("RatingId");

                    b.ToTable("tblMovie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("69a9e53a-88d0-4432-abc9-a36c4e9bfb82"),
                            Cost = 6.9900000000000002,
                            Description = "Rocky is a 1976 American sports drama film directed by John G. Avildsen, written by and starring Sylvester Stallone.",
                            DirectorId = new Guid("82c72373-7dd2-4c75-95f1-a98feed67835"),
                            FormatId = new Guid("74503613-bded-4a75-8edc-29246e0597fe"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("2c425159-927f-450f-bcc2-5f133be6b888"),
                            Title = "Rocky"
                        },
                        new
                        {
                            Id = new Guid("3b0cf02d-727d-4826-8b1b-c1da1bf1f0ec"),
                            Cost = 6.9900000000000002,
                            Description = "Other",
                            DirectorId = new Guid("82c72373-7dd2-4c75-95f1-a98feed67835"),
                            FormatId = new Guid("74503613-bded-4a75-8edc-29246e0597fe"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("2c425159-927f-450f-bcc2-5f133be6b888"),
                            Title = "Other"
                        },
                        new
                        {
                            Id = new Guid("c90e9084-21c3-46b0-82f6-43fca5421cb2"),
                            Cost = 8.9900000000000002,
                            Description = "Jaws is a 1975 American thriller film directed by Steven Spielberg and based on the Peter Benchley 1974 novel of the same name.",
                            DirectorId = new Guid("a882e5ae-aecc-433f-a4e1-706f4acdf76b"),
                            FormatId = new Guid("c547a498-d8a7-4a04-a3b8-235fdb0c8fa2"),
                            ImagePath = "Jaws1.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("68b55e4b-f31a-4ace-8a93-744f648e7ef6"),
                            Title = "Jaws"
                        },
                        new
                        {
                            Id = new Guid("5da8c185-1073-45f2-972e-edbb59af9091"),
                            Cost = 12.5,
                            Description = "The Princess Bride is a 1987 American fantasy adventure comedy film directed and co-produced by Rob Reiner, starring Cary Elwes, Robin Wright, Mandy Patinkin, Chris Sarandon, Wallace Shawn, André the Giant, and Christopher Guest.",
                            DirectorId = new Guid("07b131b9-1add-4473-9528-2941f5655992"),
                            FormatId = new Guid("60827f42-c368-4fef-ba34-610b68626694"),
                            ImagePath = "PrincessBride.jpg",
                            InStkQty = 4,
                            RatingId = new Guid("27589f2c-4b75-4cd0-96ad-947261996250"),
                            Title = "The Princess Bride"
                        },
                        new
                        {
                            Id = new Guid("9926feee-0d0f-4948-8bd2-9bc3b485b356"),
                            Cost = 10.5,
                            Description = "Indiana Jones and the Last Crusade is a 1989 American action-adventure film directed by Steven Spielberg, from a story co-written by executive producer George Lucas.",
                            DirectorId = new Guid("2c43d0de-2305-42e9-a24b-7741d2b13cf5"),
                            FormatId = new Guid("60827f42-c368-4fef-ba34-610b68626694"),
                            ImagePath = "IndianaJonesLastCrusade.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("842f3c81-b51c-4b0b-ac6a-c9b15ed0f4c2"),
                            Title = "Indiana Jones and the Last Crusade"
                        },
                        new
                        {
                            Id = new Guid("f3f856bd-bbe6-4842-96b5-40ac2c5b6c38"),
                            Cost = 7.5,
                            Description = "Star Wars: Episode IV – A New Hope is a 1977 American epic space-opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox.",
                            DirectorId = new Guid("a882e5ae-aecc-433f-a4e1-706f4acdf76b"),
                            FormatId = new Guid("c547a498-d8a7-4a04-a3b8-235fdb0c8fa2"),
                            ImagePath = "StarWarsNewHope.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("68b55e4b-f31a-4ace-8a93-744f648e7ef6"),
                            Title = "Star Wars: Episode IV – A New Hope"
                        },
                        new
                        {
                            Id = new Guid("f67938d9-6a42-4f87-8d31-f94c146a0b0a"),
                            Cost = 9.9900000000000002,
                            Description = "Pale Rider is a 1985 American Western film produced and directed by Clint Eastwood, who also stars in the lead role.",
                            DirectorId = new Guid("a882e5ae-aecc-433f-a4e1-706f4acdf76b"),
                            FormatId = new Guid("c547a498-d8a7-4a04-a3b8-235fdb0c8fa2"),
                            ImagePath = "PaleRider.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("68b55e4b-f31a-4ace-8a93-744f648e7ef6"),
                            Title = "Pale Rider"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovieGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblMovieGenre_Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblMovieGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("038aeee0-e143-4c6b-8700-3764579fdfc2"),
                            GenreId = new Guid("3e87b47b-657b-4e0b-8a55-59241604752a"),
                            MovieId = new Guid("69a9e53a-88d0-4432-abc9-a36c4e9bfb82")
                        },
                        new
                        {
                            Id = new Guid("0ba3a226-38f6-484b-97e1-dc3e6a2e8228"),
                            GenreId = new Guid("3b7f0077-9754-42d5-a440-eb3d7f9d05a7"),
                            MovieId = new Guid("69a9e53a-88d0-4432-abc9-a36c4e9bfb82")
                        },
                        new
                        {
                            Id = new Guid("664504ad-ffde-413c-98d7-8519fe4ee00f"),
                            GenreId = new Guid("8a4a0eb1-03d0-4bcc-a085-24e95ce00575"),
                            MovieId = new Guid("69a9e53a-88d0-4432-abc9-a36c4e9bfb82")
                        },
                        new
                        {
                            Id = new Guid("a13a4a9d-f645-46aa-ab7c-ec4a09319d2b"),
                            GenreId = new Guid("3e87b47b-657b-4e0b-8a55-59241604752a"),
                            MovieId = new Guid("c90e9084-21c3-46b0-82f6-43fca5421cb2")
                        },
                        new
                        {
                            Id = new Guid("de62e11d-722b-4869-8c94-836057f90062"),
                            GenreId = new Guid("3b7f0077-9754-42d5-a440-eb3d7f9d05a7"),
                            MovieId = new Guid("c90e9084-21c3-46b0-82f6-43fca5421cb2")
                        },
                        new
                        {
                            Id = new Guid("a47197b0-f415-4a85-9536-7f9b9899e7f7"),
                            GenreId = new Guid("74ad856b-3978-46b4-9c99-5ac11281d12d"),
                            MovieId = new Guid("5da8c185-1073-45f2-972e-edbb59af9091")
                        },
                        new
                        {
                            Id = new Guid("1dc99cbd-3194-44b5-8115-e0ff9b23517e"),
                            GenreId = new Guid("6419e69d-043f-466e-b320-dd4586cf00fa"),
                            MovieId = new Guid("5da8c185-1073-45f2-972e-edbb59af9091")
                        },
                        new
                        {
                            Id = new Guid("a8a6aaca-e270-4143-bd2a-03efc3def55b"),
                            GenreId = new Guid("8a4a0eb1-03d0-4bcc-a085-24e95ce00575"),
                            MovieId = new Guid("5da8c185-1073-45f2-972e-edbb59af9091")
                        },
                        new
                        {
                            Id = new Guid("38e226da-8963-4e81-bfa9-cc62a761d8cd"),
                            GenreId = new Guid("3b7f0077-9754-42d5-a440-eb3d7f9d05a7"),
                            MovieId = new Guid("9926feee-0d0f-4948-8bd2-9bc3b485b356")
                        },
                        new
                        {
                            Id = new Guid("827cca84-97ba-439a-868f-b1915304673d"),
                            GenreId = new Guid("8a4a0eb1-03d0-4bcc-a085-24e95ce00575"),
                            MovieId = new Guid("9926feee-0d0f-4948-8bd2-9bc3b485b356")
                        },
                        new
                        {
                            Id = new Guid("73a0b13c-f006-4784-9ef8-3810a4cea109"),
                            GenreId = new Guid("3b7f0077-9754-42d5-a440-eb3d7f9d05a7"),
                            MovieId = new Guid("f3f856bd-bbe6-4842-96b5-40ac2c5b6c38")
                        },
                        new
                        {
                            Id = new Guid("8cd707a2-cd8f-495f-8838-69e61a644ec3"),
                            GenreId = new Guid("24575a54-34c9-46f6-ba14-2d74c04aa7c1"),
                            MovieId = new Guid("f3f856bd-bbe6-4842-96b5-40ac2c5b6c38")
                        },
                        new
                        {
                            Id = new Guid("6a5f8d1d-777a-4cbf-a1ab-4dfbf7ff2aa4"),
                            GenreId = new Guid("acc98b10-28f1-427b-b466-0977d7ee09e1"),
                            MovieId = new Guid("f67938d9-6a42-4f87-8d31-f94c146a0b0a")
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblOrder_Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("tblOrder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("79c4c361-e49f-42e7-9c0e-63a663ac7025"),
                            CustomerId = new Guid("f38ad6db-d2c7-43a4-8151-01dc654b27da"),
                            OrderDate = new DateTime(2017, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2017, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6bf60220-ad00-45f0-921d-5e3d14b4d4e4")
                        },
                        new
                        {
                            Id = new Guid("b9ab0d66-79e5-458c-ad7f-d7802c6acf27"),
                            CustomerId = new Guid("07dc5e16-ce6e-42f9-be3b-fd5f699c2da6"),
                            OrderDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("6bf60220-ad00-45f0-921d-5e3d14b4d4e4")
                        },
                        new
                        {
                            Id = new Guid("781db6a1-16ae-43a0-864c-dc83f6112409"),
                            CustomerId = new Guid("07dc5e16-ce6e-42f9-be3b-fd5f699c2da6"),
                            OrderDate = new DateTime(2022, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("01ec4844-5259-453b-8784-f9bfe718fcf3")
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblOrderItem_Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("tblOrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("afb6bf5a-68ed-4b62-ac7a-b89f8d2d2366"),
                            Cost = 8.9900000000000002,
                            MovieId = new Guid("69a9e53a-88d0-4432-abc9-a36c4e9bfb82"),
                            OrderId = new Guid("b9ab0d66-79e5-458c-ad7f-d7802c6acf27"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("15bcdae2-4f8c-4a41-b0ba-84993fcb4ecc"),
                            Cost = 9.9900000000000002,
                            MovieId = new Guid("c90e9084-21c3-46b0-82f6-43fca5421cb2"),
                            OrderId = new Guid("b9ab0d66-79e5-458c-ad7f-d7802c6acf27"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("f772123b-dc8c-4bd7-8d27-f8eacd02e238"),
                            Cost = 10.99,
                            MovieId = new Guid("c90e9084-21c3-46b0-82f6-43fca5421cb2"),
                            OrderId = new Guid("781db6a1-16ae-43a0-864c-dc83f6112409"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblRating_Id");

                    b.ToTable("tblRating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c425159-927f-450f-bcc2-5f133be6b888"),
                            Description = "G"
                        },
                        new
                        {
                            Id = new Guid("68b55e4b-f31a-4ace-8a93-744f648e7ef6"),
                            Description = "PG-13"
                        },
                        new
                        {
                            Id = new Guid("27589f2c-4b75-4cd0-96ad-947261996250"),
                            Description = "PG"
                        },
                        new
                        {
                            Id = new Guid("842f3c81-b51c-4b0b-ac6a-c9b15ed0f4c2"),
                            Description = "R"
                        },
                        new
                        {
                            Id = new Guid("ec573346-db6b-4cd1-a070-169aee2d6669"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4aaad1ee-15fa-4d81-8717-6b9317059137"),
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "smarin"
                        },
                        new
                        {
                            Id = new Guid("6bf60220-ad00-45f0-921d-5e3d14b4d4e4"),
                            FirstName = "John",
                            LastName = "Doro",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "jdoro"
                        },
                        new
                        {
                            Id = new Guid("01ec4844-5259-453b-8784-f9bfe718fcf3"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "bfoote"
                        },
                        new
                        {
                            Id = new Guid("573f46c8-10f5-4a50-af6b-412c3c50ba8c"),
                            FirstName = "Other",
                            LastName = "Other",
                            Password = "X1BEO/529yeajg8vCpiXXNv/OOk=",
                            UserId = "sophie"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblUser", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_tblCustomer_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblDirector", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_DirectorId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblFormat", "Format")
                        .WithMany("Movies")
                        .HasForeignKey("FormatId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_FormatId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblRating", "Rating")
                        .WithMany("Movies")
                        .HasForeignKey("RatingId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_RatingId");

                    b.Navigation("Director");

                    b.Navigation("Format");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovieGenre", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblGenre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_GenreId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblMovie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_MovieId");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblCustomer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_tblOrder_CustomerId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrderItem", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblMovie", "Movie")
                        .WithMany("OrderItems")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_tblOrderItem_OrderId");

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblDirector", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblFormat", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblGenre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblRating", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
