// <auto-generated />
using System;
using BDF.DVDCentral.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDF.DVDCentral.PL.Migrations
{
    [DbContext(typeof(DVDCentralEntities))]
    [Migration("20260120191706_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_tblCustomer_Id");

                    b.ToTable("tblCustomer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9206012-e932-4b81-b5b1-9702f07bb50d"),
                            Address = "453 Oak Street",
                            City = "Fond du Lac",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Phone = "9205879797",
                            State = "WI",
                            UserId = new Guid("8a881c24-fca7-4ef2-99a9-1acc4606c763"),
                            Zip = "54935"
                        },
                        new
                        {
                            Id = new Guid("9774781c-d9d0-418b-8d34-a74a72e3a930"),
                            Address = "987 Willow Road",
                            City = "Slinger",
                            FirstName = "John",
                            LastName = "Doro",
                            Phone = "9202623345",
                            State = "WI",
                            UserId = new Guid("5051dd18-3f2f-4994-88dc-ddad097dce98"),
                            Zip = "56495"
                        },
                        new
                        {
                            Id = new Guid("56d46d8c-6e38-4d1a-83f5-7d23c3f97f2f"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Brian",
                            LastName = "Foote",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("064a9ab2-c3f9-4762-8725-211a410ec121"),
                            Zip = "53142"
                        },
                        new
                        {
                            Id = new Guid("12176b73-8682-44cc-b25b-256188972aa7"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Other",
                            LastName = "Other",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("064a9ab2-c3f9-4762-8725-211a410ec121"),
                            Zip = "53142"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblDirector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblDirector_Id");

                    b.ToTable("tblDirector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a91cba8e-088d-4fd2-a866-fcaa6c081e86"),
                            FirstName = "John",
                            LastName = "Avildsen"
                        },
                        new
                        {
                            Id = new Guid("315d99c7-4c21-47fb-a595-9944975f8d93"),
                            FirstName = "Steven",
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = new Guid("3db2f963-8fe4-46f5-8566-beeb8608b86a"),
                            FirstName = "Rob",
                            LastName = "Reiner"
                        },
                        new
                        {
                            Id = new Guid("696580b1-6f25-452d-b6b5-abc3e69934cc"),
                            FirstName = "George",
                            LastName = "Lucas"
                        },
                        new
                        {
                            Id = new Guid("b8a60bf1-33c1-412b-9f17-464e55d606d8"),
                            FirstName = "Clint",
                            LastName = "Eastwood"
                        },
                        new
                        {
                            Id = new Guid("afc2ab30-36d1-4c05-8cb8-d71f796e5025"),
                            FirstName = "Other",
                            LastName = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblFormat_Id");

                    b.ToTable("tblFormat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b88fdfe-7239-4f77-a043-c50cceebdabe"),
                            Description = "VHS"
                        },
                        new
                        {
                            Id = new Guid("9ce50789-8e1c-432d-81d1-96aa151fcaca"),
                            Description = "DVD"
                        },
                        new
                        {
                            Id = new Guid("05fca4b0-d9f4-4464-bead-8da1db25f707"),
                            Description = "Blu-Ray"
                        },
                        new
                        {
                            Id = new Guid("906f9375-60e8-49bf-82bc-6a6c2240cb38"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGenre_Id");

                    b.ToTable("tblGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("09889e20-531c-4258-a177-0bbca611099d"),
                            Description = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("0ac4af58-5882-4547-b55d-1ec19bbb9528"),
                            Description = "Action"
                        },
                        new
                        {
                            Id = new Guid("573ea92b-1419-4a9b-8b9d-a26330ed0d1b"),
                            Description = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("b37a851c-d258-424e-9505-70a9a8e1c7a2"),
                            Description = "Horror"
                        },
                        new
                        {
                            Id = new Guid("4766a066-a130-4b81-bb80-4bda7165413f"),
                            Description = "Romance"
                        },
                        new
                        {
                            Id = new Guid("798ae005-3b38-401a-90f8-357f6dd8e3e6"),
                            Description = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("7fdd941c-249f-4d02-a3d5-ebdf054d6912"),
                            Description = "Musical"
                        },
                        new
                        {
                            Id = new Guid("0a5369f8-f7a7-4002-8643-d6d46a1776f0"),
                            Description = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("1463e903-2e0e-450b-ae96-07e1b823ddf2"),
                            Description = "Western"
                        },
                        new
                        {
                            Id = new Guid("2c6fa4b5-e371-40eb-ace2-d64709f3ea8b"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("InStkQty")
                        .HasColumnType("int");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMovie_Id");

                    b.ToTable("tblMovie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77824d82-82b6-4cdf-a769-ec56b1b6c356"),
                            Cost = 6.9900000000000002,
                            Description = "Rocky is a 1976 American sports drama film directed by John G. Avildsen, written by and starring Sylvester Stallone.",
                            DirectorId = new Guid("a91cba8e-088d-4fd2-a866-fcaa6c081e86"),
                            FormatId = new Guid("3b88fdfe-7239-4f77-a043-c50cceebdabe"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("b8d9370b-ab2a-46f4-8eae-db3583c7a49c"),
                            Title = "Rocky"
                        },
                        new
                        {
                            Id = new Guid("e99bbbf5-6aa3-4ae2-b5c0-0b4423eb169e"),
                            Cost = 6.9900000000000002,
                            Description = "Other",
                            DirectorId = new Guid("a91cba8e-088d-4fd2-a866-fcaa6c081e86"),
                            FormatId = new Guid("3b88fdfe-7239-4f77-a043-c50cceebdabe"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("b8d9370b-ab2a-46f4-8eae-db3583c7a49c"),
                            Title = "Other"
                        },
                        new
                        {
                            Id = new Guid("45cc25ff-57b6-48ad-b0d3-cc7692f53eee"),
                            Cost = 8.9900000000000002,
                            Description = "Jaws is a 1975 American thriller film directed by Steven Spielberg and based on the Peter Benchley 1974 novel of the same name.",
                            DirectorId = new Guid("315d99c7-4c21-47fb-a595-9944975f8d93"),
                            FormatId = new Guid("9ce50789-8e1c-432d-81d1-96aa151fcaca"),
                            ImagePath = "Jaws1.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("bf9b53fe-b6f9-4077-9288-8d366ac1199c"),
                            Title = "Jaws"
                        },
                        new
                        {
                            Id = new Guid("9b90cc6e-1c59-436e-aa6c-f6a5770d36ec"),
                            Cost = 12.5,
                            Description = "The Princess Bride is a 1987 American fantasy adventure comedy film directed and co-produced by Rob Reiner, starring Cary Elwes, Robin Wright, Mandy Patinkin, Chris Sarandon, Wallace Shawn, André the Giant, and Christopher Guest.",
                            DirectorId = new Guid("3db2f963-8fe4-46f5-8566-beeb8608b86a"),
                            FormatId = new Guid("05fca4b0-d9f4-4464-bead-8da1db25f707"),
                            ImagePath = "PrincessBride.jpg",
                            InStkQty = 4,
                            RatingId = new Guid("118ea8d9-aa86-436e-8616-d00c946caf18"),
                            Title = "The Princess Bride"
                        },
                        new
                        {
                            Id = new Guid("83d4046b-69e5-4701-813a-e7cbc0d984cd"),
                            Cost = 10.5,
                            Description = "Indiana Jones and the Last Crusade is a 1989 American action-adventure film directed by Steven Spielberg, from a story co-written by executive producer George Lucas.",
                            DirectorId = new Guid("696580b1-6f25-452d-b6b5-abc3e69934cc"),
                            FormatId = new Guid("05fca4b0-d9f4-4464-bead-8da1db25f707"),
                            ImagePath = "IndianaJonesLastCrusade.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("4ae04e4b-7816-4e18-bf71-54c5437c6356"),
                            Title = "Indiana Jones and the Last Crusade"
                        },
                        new
                        {
                            Id = new Guid("bdac7d92-bb6c-402e-b53b-be9156ca58df"),
                            Cost = 7.5,
                            Description = "Star Wars: Episode IV – A New Hope is a 1977 American epic space-opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox.",
                            DirectorId = new Guid("315d99c7-4c21-47fb-a595-9944975f8d93"),
                            FormatId = new Guid("9ce50789-8e1c-432d-81d1-96aa151fcaca"),
                            ImagePath = "StarWarsNewHope.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("bf9b53fe-b6f9-4077-9288-8d366ac1199c"),
                            Title = "Star Wars: Episode IV – A New Hope"
                        },
                        new
                        {
                            Id = new Guid("6a89be25-06c3-4e6b-9616-03ad4714e685"),
                            Cost = 9.9900000000000002,
                            Description = "Pale Rider is a 1985 American Western film produced and directed by Clint Eastwood, who also stars in the lead role.",
                            DirectorId = new Guid("315d99c7-4c21-47fb-a595-9944975f8d93"),
                            FormatId = new Guid("9ce50789-8e1c-432d-81d1-96aa151fcaca"),
                            ImagePath = "PaleRider.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("bf9b53fe-b6f9-4077-9288-8d366ac1199c"),
                            Title = "Pale Rider"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovieGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblMovieGenre_Id");

                    b.ToTable("tblMovieGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("63a87660-9a62-44f2-bdaf-a49e1fb5054d"),
                            GenreId = new Guid("573ea92b-1419-4a9b-8b9d-a26330ed0d1b"),
                            MovieId = new Guid("77824d82-82b6-4cdf-a769-ec56b1b6c356")
                        },
                        new
                        {
                            Id = new Guid("46cd753e-d141-4eba-aa8b-f7ef514ab07c"),
                            GenreId = new Guid("b37a851c-d258-424e-9505-70a9a8e1c7a2"),
                            MovieId = new Guid("77824d82-82b6-4cdf-a769-ec56b1b6c356")
                        },
                        new
                        {
                            Id = new Guid("2ce93fdf-7a08-4edb-b027-b5ec04f85768"),
                            GenreId = new Guid("798ae005-3b38-401a-90f8-357f6dd8e3e6"),
                            MovieId = new Guid("77824d82-82b6-4cdf-a769-ec56b1b6c356")
                        },
                        new
                        {
                            Id = new Guid("ef8f1d6d-aae3-4cb9-95a9-0a66fcfce664"),
                            GenreId = new Guid("573ea92b-1419-4a9b-8b9d-a26330ed0d1b"),
                            MovieId = new Guid("45cc25ff-57b6-48ad-b0d3-cc7692f53eee")
                        },
                        new
                        {
                            Id = new Guid("9fa7a9a4-99b6-4f57-a1e1-b088df1e7dbf"),
                            GenreId = new Guid("b37a851c-d258-424e-9505-70a9a8e1c7a2"),
                            MovieId = new Guid("45cc25ff-57b6-48ad-b0d3-cc7692f53eee")
                        },
                        new
                        {
                            Id = new Guid("e52c2c0e-b92e-4437-94e3-580928d96fdd"),
                            GenreId = new Guid("09889e20-531c-4258-a177-0bbca611099d"),
                            MovieId = new Guid("9b90cc6e-1c59-436e-aa6c-f6a5770d36ec")
                        },
                        new
                        {
                            Id = new Guid("31ca17c0-8fb2-4440-a4ad-07be975ab236"),
                            GenreId = new Guid("0ac4af58-5882-4547-b55d-1ec19bbb9528"),
                            MovieId = new Guid("9b90cc6e-1c59-436e-aa6c-f6a5770d36ec")
                        },
                        new
                        {
                            Id = new Guid("2e930790-caf7-4f80-a694-eb56f1608134"),
                            GenreId = new Guid("798ae005-3b38-401a-90f8-357f6dd8e3e6"),
                            MovieId = new Guid("9b90cc6e-1c59-436e-aa6c-f6a5770d36ec")
                        },
                        new
                        {
                            Id = new Guid("a54b9117-915e-4fd9-94c8-9e73b643859a"),
                            GenreId = new Guid("b37a851c-d258-424e-9505-70a9a8e1c7a2"),
                            MovieId = new Guid("83d4046b-69e5-4701-813a-e7cbc0d984cd")
                        },
                        new
                        {
                            Id = new Guid("e60fb601-12ec-438b-bfb9-af01daf39cb1"),
                            GenreId = new Guid("798ae005-3b38-401a-90f8-357f6dd8e3e6"),
                            MovieId = new Guid("83d4046b-69e5-4701-813a-e7cbc0d984cd")
                        },
                        new
                        {
                            Id = new Guid("468c56f9-7cc5-42a6-a322-6bb6e6527db4"),
                            GenreId = new Guid("b37a851c-d258-424e-9505-70a9a8e1c7a2"),
                            MovieId = new Guid("bdac7d92-bb6c-402e-b53b-be9156ca58df")
                        },
                        new
                        {
                            Id = new Guid("1e39f8cc-58b1-40b1-ad4c-7550e27c8f30"),
                            GenreId = new Guid("7fdd941c-249f-4d02-a3d5-ebdf054d6912"),
                            MovieId = new Guid("bdac7d92-bb6c-402e-b53b-be9156ca58df")
                        },
                        new
                        {
                            Id = new Guid("2d4b4397-2bf7-40c9-8db4-a5ab526389f9"),
                            GenreId = new Guid("0a5369f8-f7a7-4002-8643-d6d46a1776f0"),
                            MovieId = new Guid("6a89be25-06c3-4e6b-9616-03ad4714e685")
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblOrder_Id");

                    b.ToTable("tblOrder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ce120240-8280-4c4a-91f1-5cd83fc1140d"),
                            CustomerId = new Guid("9774781c-d9d0-418b-8d34-a74a72e3a930"),
                            OrderDate = new DateTime(2017, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2017, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("5051dd18-3f2f-4994-88dc-ddad097dce98")
                        },
                        new
                        {
                            Id = new Guid("d3f533ae-2c41-4a2c-af0e-97030318d557"),
                            CustomerId = new Guid("56d46d8c-6e38-4d1a-83f5-7d23c3f97f2f"),
                            OrderDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("5051dd18-3f2f-4994-88dc-ddad097dce98")
                        },
                        new
                        {
                            Id = new Guid("a188a96c-2bcb-4701-b3c6-fdb2871d58f8"),
                            CustomerId = new Guid("56d46d8c-6e38-4d1a-83f5-7d23c3f97f2f"),
                            OrderDate = new DateTime(2022, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("064a9ab2-c3f9-4762-8725-211a410ec121")
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblOrderItem_Id");

                    b.ToTable("tblOrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2982eaa1-8ca1-43af-b7b6-9ef3f9453b79"),
                            Cost = 8.9900000000000002,
                            MovieId = new Guid("77824d82-82b6-4cdf-a769-ec56b1b6c356"),
                            OrderId = new Guid("d3f533ae-2c41-4a2c-af0e-97030318d557"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("b2289530-8829-4c47-a0a7-dc6cefbc36dd"),
                            Cost = 9.9900000000000002,
                            MovieId = new Guid("45cc25ff-57b6-48ad-b0d3-cc7692f53eee"),
                            OrderId = new Guid("d3f533ae-2c41-4a2c-af0e-97030318d557"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("40197c7f-cf52-45d9-8aa8-6aadc3535799"),
                            Cost = 10.99,
                            MovieId = new Guid("45cc25ff-57b6-48ad-b0d3-cc7692f53eee"),
                            OrderId = new Guid("a188a96c-2bcb-4701-b3c6-fdb2871d58f8"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblRating_Id");

                    b.ToTable("tblRating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8d9370b-ab2a-46f4-8eae-db3583c7a49c"),
                            Description = "G"
                        },
                        new
                        {
                            Id = new Guid("bf9b53fe-b6f9-4077-9288-8d366ac1199c"),
                            Description = "PG-13"
                        },
                        new
                        {
                            Id = new Guid("118ea8d9-aa86-436e-8616-d00c946caf18"),
                            Description = "PG"
                        },
                        new
                        {
                            Id = new Guid("4ae04e4b-7816-4e18-bf71-54c5437c6356"),
                            Description = "R"
                        },
                        new
                        {
                            Id = new Guid("27b904f1-ca8a-433c-8646-51caec1cf297"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a881c24-fca7-4ef2-99a9-1acc4606c763"),
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "smarin"
                        },
                        new
                        {
                            Id = new Guid("5051dd18-3f2f-4994-88dc-ddad097dce98"),
                            FirstName = "John",
                            LastName = "Doro",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "jdoro"
                        },
                        new
                        {
                            Id = new Guid("064a9ab2-c3f9-4762-8725-211a410ec121"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "bfoote"
                        },
                        new
                        {
                            Id = new Guid("c5585438-0d6c-4eec-b21a-cc64c7f3c604"),
                            FirstName = "Other",
                            LastName = "Other",
                            Password = "X1BEO/529yeajg8vCpiXXNv/OOk=",
                            UserId = "sophie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
