// <auto-generated />
using System;
using BDF.DVDCentral.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDF.DVDCentral.PL.Migrations
{
    [DbContext(typeof(DVDCentralEntities))]
    [Migration("20260411150837_AddMyStoredProcedure")]
    partial class AddMyStoredProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.spGetMoviesResult", b =>
                {
                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormatDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InStkQty")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RatingDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("spGetMoviesResult");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_tblCustomer_Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblCustomer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e42de403-2576-488e-8da2-595e5ce53391"),
                            Address = "453 Oak Street",
                            City = "Fond du Lac",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Phone = "9205879797",
                            State = "WI",
                            UserId = new Guid("2f7cdf07-aba3-46f8-b772-e23e4b206b3c"),
                            Zip = "54935"
                        },
                        new
                        {
                            Id = new Guid("36cc4c6a-1b04-431c-90bc-e4b02ff27829"),
                            Address = "987 Willow Road",
                            City = "Slinger",
                            FirstName = "John",
                            LastName = "Doro",
                            Phone = "9202623345",
                            State = "WI",
                            UserId = new Guid("c9bfc8b6-5674-4c86-bc88-df5c4b2080c5"),
                            Zip = "56495"
                        },
                        new
                        {
                            Id = new Guid("29c6d19a-253b-4719-82dc-e6e51fa0e8d5"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Brian",
                            LastName = "Foote",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("51a3e110-4cb6-4302-8a4e-2e02b0fa1b2c"),
                            Zip = "53142"
                        },
                        new
                        {
                            Id = new Guid("1502d7fa-c62d-40ba-950a-3bcd6cf53034"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Other",
                            LastName = "Other",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("51a3e110-4cb6-4302-8a4e-2e02b0fa1b2c"),
                            Zip = "53142"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblDirector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblDirector_Id");

                    b.ToTable("tblDirector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dee911a9-9dec-4022-abdd-29a1f997bfd8"),
                            FirstName = "John",
                            LastName = "Avildsen"
                        },
                        new
                        {
                            Id = new Guid("3ddc8157-5ce9-4537-92c3-932bd82ed3ad"),
                            FirstName = "Steven",
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = new Guid("622b213c-c240-4ac7-adc3-feec6a001cb8"),
                            FirstName = "Rob",
                            LastName = "Reiner"
                        },
                        new
                        {
                            Id = new Guid("1fa3262c-facb-4a87-a829-258356580f24"),
                            FirstName = "George",
                            LastName = "Lucas"
                        },
                        new
                        {
                            Id = new Guid("378df2de-fd08-429e-99e8-8e89dc689bf6"),
                            FirstName = "Clint",
                            LastName = "Eastwood"
                        },
                        new
                        {
                            Id = new Guid("08854003-57d3-492a-b0f3-fa3fcf286abe"),
                            FirstName = "Other",
                            LastName = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblFormat_Id");

                    b.ToTable("tblFormat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbcb1876-5f2c-45ee-ade5-71dd9723c7f3"),
                            Description = "VHS"
                        },
                        new
                        {
                            Id = new Guid("9c13eacf-a220-4f95-84ca-8dad09982ed1"),
                            Description = "DVD"
                        },
                        new
                        {
                            Id = new Guid("36be7e9e-4901-45f3-b15d-06dd219c3483"),
                            Description = "Blu-Ray"
                        },
                        new
                        {
                            Id = new Guid("c85d45f6-f13c-4025-90e0-ce5846a32f8b"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGenre_Id");

                    b.ToTable("tblGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec2d0b8e-13b2-4005-9a2c-5fb094fe2702"),
                            Description = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("1c73ca74-a653-4de3-8fcb-4e1f1359bdf5"),
                            Description = "Action"
                        },
                        new
                        {
                            Id = new Guid("55e0ab56-c6a2-44d2-b956-ae0c60a4e000"),
                            Description = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("e79d4aeb-76b7-4063-9819-3101261d81af"),
                            Description = "Horror"
                        },
                        new
                        {
                            Id = new Guid("79b12ea8-3099-4cef-b100-91be9ce72b1e"),
                            Description = "Romance"
                        },
                        new
                        {
                            Id = new Guid("7ee91343-af4d-425d-b46c-0c8f14ab6fd8"),
                            Description = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("d28e71a2-e2de-403c-b618-8752dab8f921"),
                            Description = "Musical"
                        },
                        new
                        {
                            Id = new Guid("9d7bbe2d-d41b-4cdd-a697-7c83519ca4bd"),
                            Description = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("b3652ff2-171d-44ce-b506-cf0aae3c3285"),
                            Description = "Western"
                        },
                        new
                        {
                            Id = new Guid("7e4650e8-9431-44f9-8100-c55c9dc41e64"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("InStkQty")
                        .HasColumnType("int");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMovie_Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("RatingId");

                    b.ToTable("tblMovie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("78ce64de-8473-4443-9d11-46fc776db418"),
                            Cost = 6.9900000000000002,
                            Description = "Rocky is a 1976 American sports drama film directed by John G. Avildsen, written by and starring Sylvester Stallone.",
                            DirectorId = new Guid("dee911a9-9dec-4022-abdd-29a1f997bfd8"),
                            FormatId = new Guid("bbcb1876-5f2c-45ee-ade5-71dd9723c7f3"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("e0790961-a07f-4c86-acbe-230762b36171"),
                            Title = "Rocky"
                        },
                        new
                        {
                            Id = new Guid("16ee85f2-4eda-4fc5-955e-b0098167d9fd"),
                            Cost = 6.9900000000000002,
                            Description = "Other",
                            DirectorId = new Guid("dee911a9-9dec-4022-abdd-29a1f997bfd8"),
                            FormatId = new Guid("bbcb1876-5f2c-45ee-ade5-71dd9723c7f3"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("e0790961-a07f-4c86-acbe-230762b36171"),
                            Title = "Other"
                        },
                        new
                        {
                            Id = new Guid("38d5fcc4-39fe-422c-9f49-608c2e9e2c7c"),
                            Cost = 8.9900000000000002,
                            Description = "Jaws is a 1975 American thriller film directed by Steven Spielberg and based on the Peter Benchley 1974 novel of the same name.",
                            DirectorId = new Guid("3ddc8157-5ce9-4537-92c3-932bd82ed3ad"),
                            FormatId = new Guid("9c13eacf-a220-4f95-84ca-8dad09982ed1"),
                            ImagePath = "Jaws1.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("f4f7e340-4b54-48ef-9586-6ca967cf0b32"),
                            Title = "Jaws"
                        },
                        new
                        {
                            Id = new Guid("6d1daac8-52f5-4df1-8987-6a80c87803b5"),
                            Cost = 12.5,
                            Description = "The Princess Bride is a 1987 American fantasy adventure comedy film directed and co-produced by Rob Reiner, starring Cary Elwes, Robin Wright, Mandy Patinkin, Chris Sarandon, Wallace Shawn, André the Giant, and Christopher Guest.",
                            DirectorId = new Guid("622b213c-c240-4ac7-adc3-feec6a001cb8"),
                            FormatId = new Guid("36be7e9e-4901-45f3-b15d-06dd219c3483"),
                            ImagePath = "PrincessBride.jpg",
                            InStkQty = 4,
                            RatingId = new Guid("35f1d110-6db9-4946-84c7-26fa999e3d8d"),
                            Title = "The Princess Bride"
                        },
                        new
                        {
                            Id = new Guid("b1689e29-3578-44a8-8e4d-18ba55663a4b"),
                            Cost = 10.5,
                            Description = "Indiana Jones and the Last Crusade is a 1989 American action-adventure film directed by Steven Spielberg, from a story co-written by executive producer George Lucas.",
                            DirectorId = new Guid("1fa3262c-facb-4a87-a829-258356580f24"),
                            FormatId = new Guid("36be7e9e-4901-45f3-b15d-06dd219c3483"),
                            ImagePath = "IndianaJonesLastCrusade.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("77b4cd7e-2a9b-4ca0-941a-8ee613ffd32e"),
                            Title = "Indiana Jones and the Last Crusade"
                        },
                        new
                        {
                            Id = new Guid("8c215c6b-5faa-44e9-93e2-e5273ca6d93e"),
                            Cost = 7.5,
                            Description = "Star Wars: Episode IV – A New Hope is a 1977 American epic space-opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox.",
                            DirectorId = new Guid("3ddc8157-5ce9-4537-92c3-932bd82ed3ad"),
                            FormatId = new Guid("9c13eacf-a220-4f95-84ca-8dad09982ed1"),
                            ImagePath = "StarWarsNewHope.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("f4f7e340-4b54-48ef-9586-6ca967cf0b32"),
                            Title = "Star Wars: Episode IV – A New Hope"
                        },
                        new
                        {
                            Id = new Guid("4c015640-3c5e-4dd8-9020-01350459bf52"),
                            Cost = 9.9900000000000002,
                            Description = "Pale Rider is a 1985 American Western film produced and directed by Clint Eastwood, who also stars in the lead role.",
                            DirectorId = new Guid("3ddc8157-5ce9-4537-92c3-932bd82ed3ad"),
                            FormatId = new Guid("9c13eacf-a220-4f95-84ca-8dad09982ed1"),
                            ImagePath = "PaleRider.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("f4f7e340-4b54-48ef-9586-6ca967cf0b32"),
                            Title = "Pale Rider"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovieGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblMovieGenre_Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblMovieGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a585b868-7417-4bd0-9128-c77971c17151"),
                            GenreId = new Guid("55e0ab56-c6a2-44d2-b956-ae0c60a4e000"),
                            MovieId = new Guid("78ce64de-8473-4443-9d11-46fc776db418")
                        },
                        new
                        {
                            Id = new Guid("2cdc6da3-8e26-4cdc-a925-9544b73ad703"),
                            GenreId = new Guid("e79d4aeb-76b7-4063-9819-3101261d81af"),
                            MovieId = new Guid("78ce64de-8473-4443-9d11-46fc776db418")
                        },
                        new
                        {
                            Id = new Guid("9f683363-6249-40fd-92d2-5be78cb4fb1d"),
                            GenreId = new Guid("7ee91343-af4d-425d-b46c-0c8f14ab6fd8"),
                            MovieId = new Guid("78ce64de-8473-4443-9d11-46fc776db418")
                        },
                        new
                        {
                            Id = new Guid("59b680b6-6ab5-4205-a180-27c1d2ef39b4"),
                            GenreId = new Guid("55e0ab56-c6a2-44d2-b956-ae0c60a4e000"),
                            MovieId = new Guid("38d5fcc4-39fe-422c-9f49-608c2e9e2c7c")
                        },
                        new
                        {
                            Id = new Guid("3e36f610-f91f-4946-a3ae-48de257f2c66"),
                            GenreId = new Guid("e79d4aeb-76b7-4063-9819-3101261d81af"),
                            MovieId = new Guid("38d5fcc4-39fe-422c-9f49-608c2e9e2c7c")
                        },
                        new
                        {
                            Id = new Guid("6c1b5a28-c52b-469e-82aa-29c2b551c672"),
                            GenreId = new Guid("ec2d0b8e-13b2-4005-9a2c-5fb094fe2702"),
                            MovieId = new Guid("6d1daac8-52f5-4df1-8987-6a80c87803b5")
                        },
                        new
                        {
                            Id = new Guid("0b28bc10-9dc2-4220-b6de-3a8b65515096"),
                            GenreId = new Guid("1c73ca74-a653-4de3-8fcb-4e1f1359bdf5"),
                            MovieId = new Guid("6d1daac8-52f5-4df1-8987-6a80c87803b5")
                        },
                        new
                        {
                            Id = new Guid("7e513a49-60b1-44e6-a653-c97ce77cf92d"),
                            GenreId = new Guid("7ee91343-af4d-425d-b46c-0c8f14ab6fd8"),
                            MovieId = new Guid("6d1daac8-52f5-4df1-8987-6a80c87803b5")
                        },
                        new
                        {
                            Id = new Guid("a7a3a48e-01ad-4993-94a8-c53bdba88c75"),
                            GenreId = new Guid("e79d4aeb-76b7-4063-9819-3101261d81af"),
                            MovieId = new Guid("b1689e29-3578-44a8-8e4d-18ba55663a4b")
                        },
                        new
                        {
                            Id = new Guid("138be0a1-ab84-4627-adac-cf0355e9c75c"),
                            GenreId = new Guid("7ee91343-af4d-425d-b46c-0c8f14ab6fd8"),
                            MovieId = new Guid("b1689e29-3578-44a8-8e4d-18ba55663a4b")
                        },
                        new
                        {
                            Id = new Guid("08ccfbeb-a00f-4929-8186-82202d148927"),
                            GenreId = new Guid("e79d4aeb-76b7-4063-9819-3101261d81af"),
                            MovieId = new Guid("8c215c6b-5faa-44e9-93e2-e5273ca6d93e")
                        },
                        new
                        {
                            Id = new Guid("5c7da3c9-a390-4b4f-a57f-677d2b632ee9"),
                            GenreId = new Guid("d28e71a2-e2de-403c-b618-8752dab8f921"),
                            MovieId = new Guid("8c215c6b-5faa-44e9-93e2-e5273ca6d93e")
                        },
                        new
                        {
                            Id = new Guid("fb66407c-7c8b-4df2-b5ff-551cab117e1d"),
                            GenreId = new Guid("9d7bbe2d-d41b-4cdd-a697-7c83519ca4bd"),
                            MovieId = new Guid("4c015640-3c5e-4dd8-9020-01350459bf52")
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblOrder_Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("tblOrder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d92bb350-aa62-472f-8168-217ac1cbddde"),
                            CustomerId = new Guid("36cc4c6a-1b04-431c-90bc-e4b02ff27829"),
                            OrderDate = new DateTime(2017, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2017, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("c9bfc8b6-5674-4c86-bc88-df5c4b2080c5")
                        },
                        new
                        {
                            Id = new Guid("33eb407f-d23c-40b0-8887-083f72f4e4c1"),
                            CustomerId = new Guid("29c6d19a-253b-4719-82dc-e6e51fa0e8d5"),
                            OrderDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("c9bfc8b6-5674-4c86-bc88-df5c4b2080c5")
                        },
                        new
                        {
                            Id = new Guid("f411a2ba-a7c0-430a-a8e1-6dede48f9a9f"),
                            CustomerId = new Guid("29c6d19a-253b-4719-82dc-e6e51fa0e8d5"),
                            OrderDate = new DateTime(2022, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("51a3e110-4cb6-4302-8a4e-2e02b0fa1b2c")
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblOrderItem_Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("tblOrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30eb7f90-48a8-435d-80c9-a497c7b4858f"),
                            Cost = 8.9900000000000002,
                            MovieId = new Guid("78ce64de-8473-4443-9d11-46fc776db418"),
                            OrderId = new Guid("33eb407f-d23c-40b0-8887-083f72f4e4c1"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("616e7198-0632-4f2c-a4fc-26e09a0355aa"),
                            Cost = 9.9900000000000002,
                            MovieId = new Guid("38d5fcc4-39fe-422c-9f49-608c2e9e2c7c"),
                            OrderId = new Guid("33eb407f-d23c-40b0-8887-083f72f4e4c1"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("632e641e-26af-4a89-88b2-848e0718e59b"),
                            Cost = 10.99,
                            MovieId = new Guid("38d5fcc4-39fe-422c-9f49-608c2e9e2c7c"),
                            OrderId = new Guid("f411a2ba-a7c0-430a-a8e1-6dede48f9a9f"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblRating_Id");

                    b.ToTable("tblRating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0790961-a07f-4c86-acbe-230762b36171"),
                            Description = "G"
                        },
                        new
                        {
                            Id = new Guid("f4f7e340-4b54-48ef-9586-6ca967cf0b32"),
                            Description = "PG-13"
                        },
                        new
                        {
                            Id = new Guid("35f1d110-6db9-4946-84c7-26fa999e3d8d"),
                            Description = "PG"
                        },
                        new
                        {
                            Id = new Guid("77b4cd7e-2a9b-4ca0-941a-8ee613ffd32e"),
                            Description = "R"
                        },
                        new
                        {
                            Id = new Guid("bbfb250d-4320-4e4d-9ae3-281541a25731"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f7cdf07-aba3-46f8-b772-e23e4b206b3c"),
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "smarin"
                        },
                        new
                        {
                            Id = new Guid("c9bfc8b6-5674-4c86-bc88-df5c4b2080c5"),
                            FirstName = "John",
                            LastName = "Doro",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "jdoro"
                        },
                        new
                        {
                            Id = new Guid("51a3e110-4cb6-4302-8a4e-2e02b0fa1b2c"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "bfoote"
                        },
                        new
                        {
                            Id = new Guid("e0b8d7bd-c269-462d-804c-2f725125b28c"),
                            FirstName = "Other",
                            LastName = "Other",
                            Password = "X1BEO/529yeajg8vCpiXXNv/OOk=",
                            UserId = "sophie"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblUser", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_tblCustomer_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblDirector", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_DirectorId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblFormat", "Format")
                        .WithMany("Movies")
                        .HasForeignKey("FormatId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_FormatId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblRating", "Rating")
                        .WithMany("Movies")
                        .HasForeignKey("RatingId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_RatingId");

                    b.Navigation("Director");

                    b.Navigation("Format");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovieGenre", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblGenre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_GenreId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblMovie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_MovieId");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblCustomer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_tblOrder_CustomerId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrderItem", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblMovie", "Movie")
                        .WithMany("OrderItems")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_tblOrderItem_OrderId");

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblDirector", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblFormat", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblGenre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblRating", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
