// <auto-generated />
using System;
using BDF.DVDCentral.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDF.DVDCentral.PL.Migrations
{
    [DbContext(typeof(DVDCentralEntities))]
    partial class DVDCentralEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_tblCustomer_Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblCustomer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab5c14a4-5cc1-4d33-a0e8-bdfd645edb21"),
                            Address = "453 Oak Street",
                            City = "Fond du Lac",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Phone = "9205879797",
                            State = "WI",
                            UserId = new Guid("b2a6d8ee-baef-475d-8b69-8a801c1f1df3"),
                            Zip = "54935"
                        },
                        new
                        {
                            Id = new Guid("1d530b0f-2e5e-48d1-9432-1506d07af0ee"),
                            Address = "987 Willow Road",
                            City = "Slinger",
                            FirstName = "John",
                            LastName = "Doro",
                            Phone = "9202623345",
                            State = "WI",
                            UserId = new Guid("af0c6cae-232e-4374-b987-8f1b1926d0f8"),
                            Zip = "56495"
                        },
                        new
                        {
                            Id = new Guid("0d25ae19-5f37-4f67-872c-6ff8356b7367"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Brian",
                            LastName = "Foote",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("8ea8177b-0d8b-4485-a65d-d7d4f3355a80"),
                            Zip = "53142"
                        },
                        new
                        {
                            Id = new Guid("456f6618-3b75-4976-ba86-2b42517dbebf"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Other",
                            LastName = "Other",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("8ea8177b-0d8b-4485-a65d-d7d4f3355a80"),
                            Zip = "53142"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblDirector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblDirector_Id");

                    b.ToTable("tblDirector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b834fe5-6fff-4997-ba55-d9fcafcf468f"),
                            FirstName = "John",
                            LastName = "Avildsen"
                        },
                        new
                        {
                            Id = new Guid("aa53c8eb-341c-455c-83b6-c6bdf63c65bc"),
                            FirstName = "Steven",
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = new Guid("14e12a61-7686-4ab8-b52d-e0b5326ffb0a"),
                            FirstName = "Rob",
                            LastName = "Reiner"
                        },
                        new
                        {
                            Id = new Guid("2192ce1b-d58b-42bf-a3d0-9541d978e02e"),
                            FirstName = "George",
                            LastName = "Lucas"
                        },
                        new
                        {
                            Id = new Guid("2aae61f2-e655-496d-957b-0fb9fa04eeb0"),
                            FirstName = "Clint",
                            LastName = "Eastwood"
                        },
                        new
                        {
                            Id = new Guid("cebf514d-5c31-45f1-af7d-ee05c3240961"),
                            FirstName = "Other",
                            LastName = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblFormat_Id");

                    b.ToTable("tblFormat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e9ccf22-c4e6-4cd7-86b3-cea3615b4593"),
                            Description = "VHS"
                        },
                        new
                        {
                            Id = new Guid("ddc2c9f4-9924-4b5d-a069-fa94d5612ec2"),
                            Description = "DVD"
                        },
                        new
                        {
                            Id = new Guid("b54b8fbf-912a-4b2f-883f-21cd7890de08"),
                            Description = "Blu-Ray"
                        },
                        new
                        {
                            Id = new Guid("b5b7fc65-43ad-4d4e-9849-034f4f5de04c"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGenre_Id");

                    b.ToTable("tblGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4940bdbc-0669-40f3-b0a1-0297bfa68889"),
                            Description = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("d02a8a04-b776-41e7-84f5-45f8c001ddcb"),
                            Description = "Action"
                        },
                        new
                        {
                            Id = new Guid("856146aa-cb28-4118-8e01-5a0d7fe4c078"),
                            Description = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("70de320c-bc5a-46ed-b7ce-3759bddee213"),
                            Description = "Horror"
                        },
                        new
                        {
                            Id = new Guid("4ad4270b-e1fc-401d-bb47-5dd3240a7582"),
                            Description = "Romance"
                        },
                        new
                        {
                            Id = new Guid("bd973808-5459-40cb-9b0a-c097bf8dd51f"),
                            Description = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("8b1f45e3-94ff-4de3-91d1-750bae029ae3"),
                            Description = "Musical"
                        },
                        new
                        {
                            Id = new Guid("a08dd089-c643-40f3-af07-f7203f73b8e7"),
                            Description = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("206c6b8a-153f-4865-a21b-1ca05883b442"),
                            Description = "Western"
                        },
                        new
                        {
                            Id = new Guid("11223866-4298-486f-99dc-f2c5d90d4e36"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("InStkQty")
                        .HasColumnType("int");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMovie_Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("RatingId");

                    b.ToTable("tblMovie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a175333c-62e2-4e59-96ef-0df176b35b68"),
                            Cost = 6.9900000000000002,
                            Description = "Rocky is a 1976 American sports drama film directed by John G. Avildsen, written by and starring Sylvester Stallone.",
                            DirectorId = new Guid("9b834fe5-6fff-4997-ba55-d9fcafcf468f"),
                            FormatId = new Guid("3e9ccf22-c4e6-4cd7-86b3-cea3615b4593"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("11e5c391-9ea7-494f-966c-5cc622bc2a05"),
                            Title = "Rocky"
                        },
                        new
                        {
                            Id = new Guid("0bddd30b-c549-4b36-91d3-023909e59231"),
                            Cost = 6.9900000000000002,
                            Description = "Other",
                            DirectorId = new Guid("9b834fe5-6fff-4997-ba55-d9fcafcf468f"),
                            FormatId = new Guid("3e9ccf22-c4e6-4cd7-86b3-cea3615b4593"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("11e5c391-9ea7-494f-966c-5cc622bc2a05"),
                            Title = "Other"
                        },
                        new
                        {
                            Id = new Guid("77bd3f3a-70e2-46ad-a0a3-16d3297fc86e"),
                            Cost = 8.9900000000000002,
                            Description = "Jaws is a 1975 American thriller film directed by Steven Spielberg and based on the Peter Benchley 1974 novel of the same name.",
                            DirectorId = new Guid("aa53c8eb-341c-455c-83b6-c6bdf63c65bc"),
                            FormatId = new Guid("ddc2c9f4-9924-4b5d-a069-fa94d5612ec2"),
                            ImagePath = "Jaws1.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("06d3a510-1126-4e26-9bab-f7836e0b9430"),
                            Title = "Jaws"
                        },
                        new
                        {
                            Id = new Guid("1e058a09-763c-4a30-b862-2436a7611d02"),
                            Cost = 12.5,
                            Description = "The Princess Bride is a 1987 American fantasy adventure comedy film directed and co-produced by Rob Reiner, starring Cary Elwes, Robin Wright, Mandy Patinkin, Chris Sarandon, Wallace Shawn, André the Giant, and Christopher Guest.",
                            DirectorId = new Guid("14e12a61-7686-4ab8-b52d-e0b5326ffb0a"),
                            FormatId = new Guid("b54b8fbf-912a-4b2f-883f-21cd7890de08"),
                            ImagePath = "PrincessBride.jpg",
                            InStkQty = 4,
                            RatingId = new Guid("093721dc-f8b2-4ac6-bce5-db0e0d390002"),
                            Title = "The Princess Bride"
                        },
                        new
                        {
                            Id = new Guid("4f2641e5-aee3-4886-a83b-f5c6f5decde3"),
                            Cost = 10.5,
                            Description = "Indiana Jones and the Last Crusade is a 1989 American action-adventure film directed by Steven Spielberg, from a story co-written by executive producer George Lucas.",
                            DirectorId = new Guid("2192ce1b-d58b-42bf-a3d0-9541d978e02e"),
                            FormatId = new Guid("b54b8fbf-912a-4b2f-883f-21cd7890de08"),
                            ImagePath = "IndianaJonesLastCrusade.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("8319f572-0b50-4595-843d-3ea72dffa6b6"),
                            Title = "Indiana Jones and the Last Crusade"
                        },
                        new
                        {
                            Id = new Guid("83039748-b641-48f4-a729-878c19321779"),
                            Cost = 7.5,
                            Description = "Star Wars: Episode IV – A New Hope is a 1977 American epic space-opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox.",
                            DirectorId = new Guid("aa53c8eb-341c-455c-83b6-c6bdf63c65bc"),
                            FormatId = new Guid("ddc2c9f4-9924-4b5d-a069-fa94d5612ec2"),
                            ImagePath = "StarWarsNewHope.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("06d3a510-1126-4e26-9bab-f7836e0b9430"),
                            Title = "Star Wars: Episode IV – A New Hope"
                        },
                        new
                        {
                            Id = new Guid("1d659b3e-4c4f-49a3-9ea1-4253b944bb89"),
                            Cost = 9.9900000000000002,
                            Description = "Pale Rider is a 1985 American Western film produced and directed by Clint Eastwood, who also stars in the lead role.",
                            DirectorId = new Guid("aa53c8eb-341c-455c-83b6-c6bdf63c65bc"),
                            FormatId = new Guid("ddc2c9f4-9924-4b5d-a069-fa94d5612ec2"),
                            ImagePath = "PaleRider.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("06d3a510-1126-4e26-9bab-f7836e0b9430"),
                            Title = "Pale Rider"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovieGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblMovieGenre_Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblMovieGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("76453fe9-1c51-4b6e-b9be-b7c337074da1"),
                            GenreId = new Guid("856146aa-cb28-4118-8e01-5a0d7fe4c078"),
                            MovieId = new Guid("a175333c-62e2-4e59-96ef-0df176b35b68")
                        },
                        new
                        {
                            Id = new Guid("7abff031-9243-4974-8115-e0f81537d40e"),
                            GenreId = new Guid("70de320c-bc5a-46ed-b7ce-3759bddee213"),
                            MovieId = new Guid("a175333c-62e2-4e59-96ef-0df176b35b68")
                        },
                        new
                        {
                            Id = new Guid("bfbe750f-c78b-4610-b9a5-e77ff288b496"),
                            GenreId = new Guid("bd973808-5459-40cb-9b0a-c097bf8dd51f"),
                            MovieId = new Guid("a175333c-62e2-4e59-96ef-0df176b35b68")
                        },
                        new
                        {
                            Id = new Guid("0967604f-3bbb-4d5b-9398-abf1a68884b4"),
                            GenreId = new Guid("856146aa-cb28-4118-8e01-5a0d7fe4c078"),
                            MovieId = new Guid("77bd3f3a-70e2-46ad-a0a3-16d3297fc86e")
                        },
                        new
                        {
                            Id = new Guid("c26e0e92-e4c3-4fc1-b4f6-b3d6cb297b92"),
                            GenreId = new Guid("70de320c-bc5a-46ed-b7ce-3759bddee213"),
                            MovieId = new Guid("77bd3f3a-70e2-46ad-a0a3-16d3297fc86e")
                        },
                        new
                        {
                            Id = new Guid("bc2d27ef-eef2-473e-a87b-e283f97e84b5"),
                            GenreId = new Guid("4940bdbc-0669-40f3-b0a1-0297bfa68889"),
                            MovieId = new Guid("1e058a09-763c-4a30-b862-2436a7611d02")
                        },
                        new
                        {
                            Id = new Guid("7fc88c92-c921-4245-a92d-403732691e0c"),
                            GenreId = new Guid("d02a8a04-b776-41e7-84f5-45f8c001ddcb"),
                            MovieId = new Guid("1e058a09-763c-4a30-b862-2436a7611d02")
                        },
                        new
                        {
                            Id = new Guid("9a3a4bb3-7567-43b3-b05a-c8e29d17c26b"),
                            GenreId = new Guid("bd973808-5459-40cb-9b0a-c097bf8dd51f"),
                            MovieId = new Guid("1e058a09-763c-4a30-b862-2436a7611d02")
                        },
                        new
                        {
                            Id = new Guid("bcda6e98-2cab-4b78-9396-3d5d0572c98e"),
                            GenreId = new Guid("70de320c-bc5a-46ed-b7ce-3759bddee213"),
                            MovieId = new Guid("4f2641e5-aee3-4886-a83b-f5c6f5decde3")
                        },
                        new
                        {
                            Id = new Guid("107729ad-3890-42fd-80eb-ecc19bc0ce92"),
                            GenreId = new Guid("bd973808-5459-40cb-9b0a-c097bf8dd51f"),
                            MovieId = new Guid("4f2641e5-aee3-4886-a83b-f5c6f5decde3")
                        },
                        new
                        {
                            Id = new Guid("06a35923-e293-4f2d-865b-7ddc3e3d38bc"),
                            GenreId = new Guid("70de320c-bc5a-46ed-b7ce-3759bddee213"),
                            MovieId = new Guid("83039748-b641-48f4-a729-878c19321779")
                        },
                        new
                        {
                            Id = new Guid("020177e8-a4c7-4349-8fcc-bc58f1687636"),
                            GenreId = new Guid("8b1f45e3-94ff-4de3-91d1-750bae029ae3"),
                            MovieId = new Guid("83039748-b641-48f4-a729-878c19321779")
                        },
                        new
                        {
                            Id = new Guid("78ee0a68-bab7-4fe6-8ca0-3cf2820a53d4"),
                            GenreId = new Guid("a08dd089-c643-40f3-af07-f7203f73b8e7"),
                            MovieId = new Guid("1d659b3e-4c4f-49a3-9ea1-4253b944bb89")
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblOrder_Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("tblOrder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1243f5fe-ec85-4c56-a281-35f61d167193"),
                            CustomerId = new Guid("1d530b0f-2e5e-48d1-9432-1506d07af0ee"),
                            OrderDate = new DateTime(2017, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2017, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("af0c6cae-232e-4374-b987-8f1b1926d0f8")
                        },
                        new
                        {
                            Id = new Guid("bbce3197-c764-4ca5-a9a4-5b4375b00db5"),
                            CustomerId = new Guid("0d25ae19-5f37-4f67-872c-6ff8356b7367"),
                            OrderDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("af0c6cae-232e-4374-b987-8f1b1926d0f8")
                        },
                        new
                        {
                            Id = new Guid("dbb17e94-c308-4311-9aae-ab7bc784aee0"),
                            CustomerId = new Guid("0d25ae19-5f37-4f67-872c-6ff8356b7367"),
                            OrderDate = new DateTime(2022, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("8ea8177b-0d8b-4485-a65d-d7d4f3355a80")
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblOrderItem_Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("tblOrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("732a12d3-3432-4999-86f6-7c3e4da7d166"),
                            Cost = 8.9900000000000002,
                            MovieId = new Guid("a175333c-62e2-4e59-96ef-0df176b35b68"),
                            OrderId = new Guid("bbce3197-c764-4ca5-a9a4-5b4375b00db5"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("60a1e82a-83bc-4ec2-8cae-48d598db3882"),
                            Cost = 9.9900000000000002,
                            MovieId = new Guid("77bd3f3a-70e2-46ad-a0a3-16d3297fc86e"),
                            OrderId = new Guid("bbce3197-c764-4ca5-a9a4-5b4375b00db5"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("ae99302d-1ee1-4764-9e03-a815d4acbccc"),
                            Cost = 10.99,
                            MovieId = new Guid("77bd3f3a-70e2-46ad-a0a3-16d3297fc86e"),
                            OrderId = new Guid("dbb17e94-c308-4311-9aae-ab7bc784aee0"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblRating_Id");

                    b.ToTable("tblRating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11e5c391-9ea7-494f-966c-5cc622bc2a05"),
                            Description = "G"
                        },
                        new
                        {
                            Id = new Guid("06d3a510-1126-4e26-9bab-f7836e0b9430"),
                            Description = "PG-13"
                        },
                        new
                        {
                            Id = new Guid("093721dc-f8b2-4ac6-bce5-db0e0d390002"),
                            Description = "PG"
                        },
                        new
                        {
                            Id = new Guid("8319f572-0b50-4595-843d-3ea72dffa6b6"),
                            Description = "R"
                        },
                        new
                        {
                            Id = new Guid("41bd2a90-ea93-45ff-afb6-5d30be30a82f"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2a6d8ee-baef-475d-8b69-8a801c1f1df3"),
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "smarin"
                        },
                        new
                        {
                            Id = new Guid("af0c6cae-232e-4374-b987-8f1b1926d0f8"),
                            FirstName = "John",
                            LastName = "Doro",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "jdoro"
                        },
                        new
                        {
                            Id = new Guid("8ea8177b-0d8b-4485-a65d-d7d4f3355a80"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "bfoote"
                        },
                        new
                        {
                            Id = new Guid("1c7bb3c2-e2b2-4203-b15b-a4ff5cf7fed5"),
                            FirstName = "Other",
                            LastName = "Other",
                            Password = "X1BEO/529yeajg8vCpiXXNv/OOk=",
                            UserId = "sophie"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblUser", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_tblCustomer_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblDirector", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_DirectorId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblFormat", "Format")
                        .WithMany("Movies")
                        .HasForeignKey("FormatId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_FormatId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblRating", "Rating")
                        .WithMany("Movies")
                        .HasForeignKey("RatingId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_RatingId");

                    b.Navigation("Director");

                    b.Navigation("Format");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovieGenre", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblGenre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_GenreId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblMovie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_MovieId");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblCustomer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_tblOrder_CustomerId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrderItem", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblMovie", "Movie")
                        .WithMany("OrderItems")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_tblOrderItem_OrderId");

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblDirector", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblFormat", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblGenre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblRating", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
