// <auto-generated />
using System;
using BDF.DVDCentral.PL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BDF.DVDCentral.PL.Migrations
{
    [DbContext(typeof(DVDCentralEntities))]
    partial class DVDCentralEntitiesModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.HasKey("Id")
                        .HasName("PK_tblCustomer_Id");

                    b.HasIndex("UserId");

                    b.ToTable("tblCustomer", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b315c88b-ed2e-4d59-8f54-0943b057643c"),
                            Address = "453 Oak Street",
                            City = "Fond du Lac",
                            FirstName = "Steve",
                            LastName = "Marin",
                            Phone = "9205879797",
                            State = "WI",
                            UserId = new Guid("259a2a2a-1006-42f9-80eb-a15a55eb1af8"),
                            Zip = "54935"
                        },
                        new
                        {
                            Id = new Guid("4a9719a8-49da-4109-80bc-e3cdfaf4a586"),
                            Address = "987 Willow Road",
                            City = "Slinger",
                            FirstName = "John",
                            LastName = "Doro",
                            Phone = "9202623345",
                            State = "WI",
                            UserId = new Guid("5e489d79-76f4-4f5d-b4ea-e39aa37fdf86"),
                            Zip = "56495"
                        },
                        new
                        {
                            Id = new Guid("8ac084ec-0d24-443a-9d7d-d80716e38eaa"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Brian",
                            LastName = "Foote",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("5c19b233-711f-467b-b932-62aca6e7e99d"),
                            Zip = "53142"
                        },
                        new
                        {
                            Id = new Guid("6bcb26ca-55ec-4a8d-b3f8-53bd27df8cda"),
                            Address = "159 Johnson Avenue",
                            City = "Allenton",
                            FirstName = "Other",
                            LastName = "Other",
                            Phone = "9202623415",
                            State = "WI",
                            UserId = new Guid("5c19b233-711f-467b-b932-62aca6e7e99d"),
                            Zip = "53142"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblDirector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblDirector_Id");

                    b.ToTable("tblDirector", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("72f2ae73-5ffd-40ca-8d7a-219b89597bed"),
                            FirstName = "John",
                            LastName = "Avildsen"
                        },
                        new
                        {
                            Id = new Guid("ec8d62eb-1c27-447f-85e9-4cebe6ff158e"),
                            FirstName = "Steven",
                            LastName = "Spielberg"
                        },
                        new
                        {
                            Id = new Guid("44151a9e-a522-41ea-b50c-6c45dc39190b"),
                            FirstName = "Rob",
                            LastName = "Reiner"
                        },
                        new
                        {
                            Id = new Guid("a5847793-5163-4a28-89ca-10c315662eca"),
                            FirstName = "George",
                            LastName = "Lucas"
                        },
                        new
                        {
                            Id = new Guid("26590f9d-72bf-4db4-91fb-3a527c8b4921"),
                            FirstName = "Clint",
                            LastName = "Eastwood"
                        },
                        new
                        {
                            Id = new Guid("f05b1751-05ce-4aa7-8e33-e886bac5d159"),
                            FirstName = "Other",
                            LastName = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblFormat_Id");

                    b.ToTable("tblFormat", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1c3a568-977b-4ad8-88fd-975c29d54965"),
                            Description = "VHS"
                        },
                        new
                        {
                            Id = new Guid("929622cc-6be9-45fa-a758-47d809fc5683"),
                            Description = "DVD"
                        },
                        new
                        {
                            Id = new Guid("fa7bf046-3d42-4b05-aa11-c3853ce3b1be"),
                            Description = "Blu-Ray"
                        },
                        new
                        {
                            Id = new Guid("a6ba33d4-fabe-4194-abef-c90cee75d291"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblGenre_Id");

                    b.ToTable("tblGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8118fca5-2e87-4bb6-9dfc-773a85a24247"),
                            Description = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("a9b3539a-eafa-4434-9331-978951ce2e2f"),
                            Description = "Action"
                        },
                        new
                        {
                            Id = new Guid("2554f62b-2153-468a-ba84-83df15147f5f"),
                            Description = "Sci-Fi"
                        },
                        new
                        {
                            Id = new Guid("cf794402-c743-494b-bfc0-58b8b3d32e85"),
                            Description = "Horror"
                        },
                        new
                        {
                            Id = new Guid("e9e2991e-b7d8-4b46-9c33-483bb0fc41c8"),
                            Description = "Romance"
                        },
                        new
                        {
                            Id = new Guid("672a0c47-d498-46a5-aa77-7fa892b2d7c4"),
                            Description = "Documentary"
                        },
                        new
                        {
                            Id = new Guid("6715bdaf-f5fa-41fc-bf2f-20f1440a001a"),
                            Description = "Musical"
                        },
                        new
                        {
                            Id = new Guid("328b62c0-2d4b-4fce-927a-b4d19689b927"),
                            Description = "Mystery"
                        },
                        new
                        {
                            Id = new Guid("93563451-319d-422d-bcdd-1225c5103020"),
                            Description = "Western"
                        },
                        new
                        {
                            Id = new Guid("d1d5ba7c-5674-4f18-9543-0dc03c6dec04"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("DirectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FormatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("InStkQty")
                        .HasColumnType("int");

                    b.Property<Guid>("RatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_tblMovie_Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("FormatId");

                    b.HasIndex("RatingId");

                    b.ToTable("tblMovie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("732d945e-1482-46cb-9abf-f097e0957d85"),
                            Cost = 6.9900000000000002,
                            Description = "Rocky is a 1976 American sports drama film directed by John G. Avildsen, written by and starring Sylvester Stallone.",
                            DirectorId = new Guid("72f2ae73-5ffd-40ca-8d7a-219b89597bed"),
                            FormatId = new Guid("d1c3a568-977b-4ad8-88fd-975c29d54965"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("f864adf7-48fd-4a67-954c-e7dbe5016b54"),
                            Title = "Rocky"
                        },
                        new
                        {
                            Id = new Guid("f5f4d76c-62f7-42bf-9f4d-625a8075cb54"),
                            Cost = 6.9900000000000002,
                            Description = "Other",
                            DirectorId = new Guid("72f2ae73-5ffd-40ca-8d7a-219b89597bed"),
                            FormatId = new Guid("d1c3a568-977b-4ad8-88fd-975c29d54965"),
                            ImagePath = "Rocky.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("f864adf7-48fd-4a67-954c-e7dbe5016b54"),
                            Title = "Other"
                        },
                        new
                        {
                            Id = new Guid("fc624838-23b0-43a9-a7b7-3c7aba189f4a"),
                            Cost = 8.9900000000000002,
                            Description = "Jaws is a 1975 American thriller film directed by Steven Spielberg and based on the Peter Benchley 1974 novel of the same name.",
                            DirectorId = new Guid("ec8d62eb-1c27-447f-85e9-4cebe6ff158e"),
                            FormatId = new Guid("929622cc-6be9-45fa-a758-47d809fc5683"),
                            ImagePath = "Jaws1.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("c5d825f6-d2ae-464e-b753-c0d90df33d35"),
                            Title = "Jaws"
                        },
                        new
                        {
                            Id = new Guid("c49b331b-34b9-4142-a198-2eb207e6a4fa"),
                            Cost = 12.5,
                            Description = "The Princess Bride is a 1987 American fantasy adventure comedy film directed and co-produced by Rob Reiner, starring Cary Elwes, Robin Wright, Mandy Patinkin, Chris Sarandon, Wallace Shawn, André the Giant, and Christopher Guest.",
                            DirectorId = new Guid("44151a9e-a522-41ea-b50c-6c45dc39190b"),
                            FormatId = new Guid("fa7bf046-3d42-4b05-aa11-c3853ce3b1be"),
                            ImagePath = "PrincessBride.jpg",
                            InStkQty = 4,
                            RatingId = new Guid("70f4de95-db5a-4748-a3c6-88d255dddec6"),
                            Title = "The Princess Bride"
                        },
                        new
                        {
                            Id = new Guid("3d0add41-5007-43d1-9b00-6b864c1a0281"),
                            Cost = 10.5,
                            Description = "Indiana Jones and the Last Crusade is a 1989 American action-adventure film directed by Steven Spielberg, from a story co-written by executive producer George Lucas.",
                            DirectorId = new Guid("a5847793-5163-4a28-89ca-10c315662eca"),
                            FormatId = new Guid("fa7bf046-3d42-4b05-aa11-c3853ce3b1be"),
                            ImagePath = "IndianaJonesLastCrusade.jpg",
                            InStkQty = 2,
                            RatingId = new Guid("064f5963-e477-4b75-b707-10f78e5fb71e"),
                            Title = "Indiana Jones and the Last Crusade"
                        },
                        new
                        {
                            Id = new Guid("bae7740e-96ce-482e-9db4-ed3ec8a0abd1"),
                            Cost = 7.5,
                            Description = "Star Wars: Episode IV – A New Hope is a 1977 American epic space-opera film written and directed by George Lucas, produced by Lucasfilm and distributed by 20th Century Fox.",
                            DirectorId = new Guid("ec8d62eb-1c27-447f-85e9-4cebe6ff158e"),
                            FormatId = new Guid("929622cc-6be9-45fa-a758-47d809fc5683"),
                            ImagePath = "StarWarsNewHope.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("c5d825f6-d2ae-464e-b753-c0d90df33d35"),
                            Title = "Star Wars: Episode IV – A New Hope"
                        },
                        new
                        {
                            Id = new Guid("5d38bc3e-ccd1-4768-aa52-4cb7eec8b987"),
                            Cost = 9.9900000000000002,
                            Description = "Pale Rider is a 1985 American Western film produced and directed by Clint Eastwood, who also stars in the lead role.",
                            DirectorId = new Guid("ec8d62eb-1c27-447f-85e9-4cebe6ff158e"),
                            FormatId = new Guid("929622cc-6be9-45fa-a758-47d809fc5683"),
                            ImagePath = "PaleRider.jpg",
                            InStkQty = 1,
                            RatingId = new Guid("c5d825f6-d2ae-464e-b753-c0d90df33d35"),
                            Title = "Pale Rider"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovieGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblMovieGenre_Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("tblMovieGenre", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe51f0af-00c9-4663-8ec4-711805bcf971"),
                            GenreId = new Guid("2554f62b-2153-468a-ba84-83df15147f5f"),
                            MovieId = new Guid("732d945e-1482-46cb-9abf-f097e0957d85")
                        },
                        new
                        {
                            Id = new Guid("131407b6-09a1-4711-9f46-897bfb789d71"),
                            GenreId = new Guid("cf794402-c743-494b-bfc0-58b8b3d32e85"),
                            MovieId = new Guid("732d945e-1482-46cb-9abf-f097e0957d85")
                        },
                        new
                        {
                            Id = new Guid("aabbf2a5-817d-4f84-8c45-34a1df8d1261"),
                            GenreId = new Guid("672a0c47-d498-46a5-aa77-7fa892b2d7c4"),
                            MovieId = new Guid("732d945e-1482-46cb-9abf-f097e0957d85")
                        },
                        new
                        {
                            Id = new Guid("d151fb6c-7051-4bfe-9a64-5ccbcef9294d"),
                            GenreId = new Guid("2554f62b-2153-468a-ba84-83df15147f5f"),
                            MovieId = new Guid("fc624838-23b0-43a9-a7b7-3c7aba189f4a")
                        },
                        new
                        {
                            Id = new Guid("7de13edf-36ad-4a81-aabf-63506e189632"),
                            GenreId = new Guid("cf794402-c743-494b-bfc0-58b8b3d32e85"),
                            MovieId = new Guid("fc624838-23b0-43a9-a7b7-3c7aba189f4a")
                        },
                        new
                        {
                            Id = new Guid("4642452c-b6aa-4674-a2cd-20baeba00dd9"),
                            GenreId = new Guid("8118fca5-2e87-4bb6-9dfc-773a85a24247"),
                            MovieId = new Guid("c49b331b-34b9-4142-a198-2eb207e6a4fa")
                        },
                        new
                        {
                            Id = new Guid("ec479098-1d5e-4be7-aca6-9c5c36ee5e65"),
                            GenreId = new Guid("a9b3539a-eafa-4434-9331-978951ce2e2f"),
                            MovieId = new Guid("c49b331b-34b9-4142-a198-2eb207e6a4fa")
                        },
                        new
                        {
                            Id = new Guid("686f5e97-cdcf-44f0-b250-22c1b1dfec38"),
                            GenreId = new Guid("672a0c47-d498-46a5-aa77-7fa892b2d7c4"),
                            MovieId = new Guid("c49b331b-34b9-4142-a198-2eb207e6a4fa")
                        },
                        new
                        {
                            Id = new Guid("204e3dd1-74d7-4dfa-9781-e4547d7012b4"),
                            GenreId = new Guid("cf794402-c743-494b-bfc0-58b8b3d32e85"),
                            MovieId = new Guid("3d0add41-5007-43d1-9b00-6b864c1a0281")
                        },
                        new
                        {
                            Id = new Guid("5d75b195-e85c-4ffb-b6e8-f88bb9df18c7"),
                            GenreId = new Guid("672a0c47-d498-46a5-aa77-7fa892b2d7c4"),
                            MovieId = new Guid("3d0add41-5007-43d1-9b00-6b864c1a0281")
                        },
                        new
                        {
                            Id = new Guid("87757825-3e9a-46c6-8ce6-0029cbe1b5dd"),
                            GenreId = new Guid("cf794402-c743-494b-bfc0-58b8b3d32e85"),
                            MovieId = new Guid("bae7740e-96ce-482e-9db4-ed3ec8a0abd1")
                        },
                        new
                        {
                            Id = new Guid("c7043aa7-c33d-4209-945e-5c0ad50f5b18"),
                            GenreId = new Guid("6715bdaf-f5fa-41fc-bf2f-20f1440a001a"),
                            MovieId = new Guid("bae7740e-96ce-482e-9db4-ed3ec8a0abd1")
                        },
                        new
                        {
                            Id = new Guid("0af105dd-484a-4207-b8c2-9d348370c2cc"),
                            GenreId = new Guid("328b62c0-2d4b-4fce-927a-b4d19689b927"),
                            MovieId = new Guid("5d38bc3e-ccd1-4768-aa52-4cb7eec8b987")
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ShipDate")
                        .HasColumnType("datetime");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_tblOrder_Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("UserId");

                    b.ToTable("tblOrder", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("229b05ca-bfa1-48e4-b6ad-25ad9f106c2e"),
                            CustomerId = new Guid("4a9719a8-49da-4109-80bc-e3cdfaf4a586"),
                            OrderDate = new DateTime(2017, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2017, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("5e489d79-76f4-4f5d-b4ea-e39aa37fdf86")
                        },
                        new
                        {
                            Id = new Guid("19f2228e-eafd-4b6e-bb67-b4742ed630d7"),
                            CustomerId = new Guid("8ac084ec-0d24-443a-9d7d-d80716e38eaa"),
                            OrderDate = new DateTime(2021, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("5e489d79-76f4-4f5d-b4ea-e39aa37fdf86")
                        },
                        new
                        {
                            Id = new Guid("3eaab255-b26f-486b-8ab1-48bb1231520d"),
                            CustomerId = new Guid("8ac084ec-0d24-443a-9d7d-d80716e38eaa"),
                            OrderDate = new DateTime(2022, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShipDate = new DateTime(2022, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("5c19b233-711f-467b-b932-62aca6e7e99d")
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_tblOrderItem_Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("OrderId");

                    b.ToTable("tblOrderItem", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2214297a-2f6d-44d6-a3e3-c725114ed47b"),
                            Cost = 8.9900000000000002,
                            MovieId = new Guid("732d945e-1482-46cb-9abf-f097e0957d85"),
                            OrderId = new Guid("19f2228e-eafd-4b6e-bb67-b4742ed630d7"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("47c6e7aa-4704-4f9e-90e9-44c40d0d856b"),
                            Cost = 9.9900000000000002,
                            MovieId = new Guid("fc624838-23b0-43a9-a7b7-3c7aba189f4a"),
                            OrderId = new Guid("19f2228e-eafd-4b6e-bb67-b4742ed630d7"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("101d324d-1091-4088-b338-042c6ae25a33"),
                            Cost = 10.99,
                            MovieId = new Guid("fc624838-23b0-43a9-a7b7-3c7aba189f4a"),
                            OrderId = new Guid("3eaab255-b26f-486b-8ab1-48bb1231520d"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_tblRating_Id");

                    b.ToTable("tblRating", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f864adf7-48fd-4a67-954c-e7dbe5016b54"),
                            Description = "G"
                        },
                        new
                        {
                            Id = new Guid("c5d825f6-d2ae-464e-b753-c0d90df33d35"),
                            Description = "PG-13"
                        },
                        new
                        {
                            Id = new Guid("70f4de95-db5a-4748-a3c6-88d255dddec6"),
                            Description = "PG"
                        },
                        new
                        {
                            Id = new Guid("064f5963-e477-4b75-b707-10f78e5fb71e"),
                            Description = "R"
                        },
                        new
                        {
                            Id = new Guid("6e78fdd2-795b-4439-9bf2-411bd03d39a9"),
                            Description = "Other"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(28)
                        .IsUnicode(false)
                        .HasColumnType("varchar(28)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id")
                        .HasName("PK_tblUser_Id");

                    b.ToTable("tblUser", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("259a2a2a-1006-42f9-80eb-a15a55eb1af8"),
                            FirstName = "Steve",
                            LastName = "Marin",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "smarin"
                        },
                        new
                        {
                            Id = new Guid("5e489d79-76f4-4f5d-b4ea-e39aa37fdf86"),
                            FirstName = "John",
                            LastName = "Doro",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "jdoro"
                        },
                        new
                        {
                            Id = new Guid("5c19b233-711f-467b-b932-62aca6e7e99d"),
                            FirstName = "Brian",
                            LastName = "Foote",
                            Password = "pYfdnNb8sO0FgS4H0MRSwLGOIME=",
                            UserId = "bfoote"
                        },
                        new
                        {
                            Id = new Guid("b6e68cf7-8fd5-43ee-bcff-0afa2bb8a88b"),
                            FirstName = "Other",
                            LastName = "Other",
                            Password = "X1BEO/529yeajg8vCpiXXNv/OOk=",
                            UserId = "sophie"
                        });
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblUser", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_tblCustomer_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblDirector", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_DirectorId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblFormat", "Format")
                        .WithMany("Movies")
                        .HasForeignKey("FormatId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_FormatId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblRating", "Rating")
                        .WithMany("Movies")
                        .HasForeignKey("RatingId")
                        .IsRequired()
                        .HasConstraintName("FK_tblMovie_RatingId");

                    b.Navigation("Director");

                    b.Navigation("Format");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovieGenre", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblGenre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_GenreId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblMovie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("tblMovieGenre_MovieId");

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblCustomer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_tblOrder_CustomerId");

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrderItem", b =>
                {
                    b.HasOne("BDF.DVDCentral.PL.Entities.tblMovie", "Movie")
                        .WithMany("OrderItems")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BDF.DVDCentral.PL.Entities.tblOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_tblOrderItem_OrderId");

                    b.Navigation("Movie");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblCustomer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblDirector", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblFormat", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblGenre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblMovie", b =>
                {
                    b.Navigation("MovieGenres");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblRating", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("BDF.DVDCentral.PL.Entities.tblUser", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
